# Generated by Django 2.2.12 on 2021-06-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=511)),
                ('zip', models.CharField(max_length=5)),
                ('hours', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
