# Generated by Django 2.2.12 on 2021-06-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bathroom_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bathroom',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
