# Generated by Django 2.2.12 on 2021-06-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bathroom_map', '0002_auto_20210608_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroom',
            name='hours',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bathroom',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='bathroom',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='bathroom',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
