# Generated by Django 2.2.12 on 2021-06-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bathroom_map', '0003_auto_20210609_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroom',
            name='hours',
            field=models.TextField(blank=True, default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bathroom',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bathroom',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bathroom',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bathroom',
            name='remarks',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
